"""init tables

Revision ID: f8df02d76289
Revises: 
Create Date: 2023-10-13 14:00:18.569747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8df02d76289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name_author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_author_author_id'), 'author', ['author_id'], unique=False)
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name_city', sa.String(), nullable=False),
    sa.Column('days_delivery', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_city_city_id'), 'city', ['city_id'], unique=False)
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name_genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genre_genre_id'), 'genre', ['genre_id'], unique=False)
    op.create_table('step',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('name_step', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_step_step_id'), 'step', ['step_id'], unique=False)
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_book_id'), 'book', ['book_id'], unique=False)
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_client_id'), 'client', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_table('buy',
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('buy_description', sa.String(), nullable=True),
    sa.Column('clien_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clien_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buy_id')
    )
    op.create_index(op.f('ix_buy_buy_id'), 'buy', ['buy_id'], unique=False)
    op.create_table('buy_book',
    sa.Column('buy_book_id', sa.Integer(), nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.buy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buy_book_id')
    )
    op.create_index(op.f('ix_buy_book_buy_book_id'), 'buy_book', ['buy_book_id'], unique=False)
    op.create_table('buy_step',
    sa.Column('buy_step_id', sa.Integer(), nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('date_step_beg', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_step_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.buy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buy_step_id')
    )
    op.create_index(op.f('ix_buy_step_buy_step_id'), 'buy_step', ['buy_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_step_buy_step_id'), table_name='buy_step')
    op.drop_table('buy_step')
    op.drop_index(op.f('ix_buy_book_buy_book_id'), table_name='buy_book')
    op.drop_table('buy_book')
    op.drop_index(op.f('ix_buy_buy_id'), table_name='buy')
    op.drop_table('buy')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index(op.f('ix_client_client_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_book_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_step_step_id'), table_name='step')
    op.drop_table('step')
    op.drop_index(op.f('ix_genre_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_city_city_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_author_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
